server:
  port: 8080
  servlet:
    context-path: /api/v1
  tomcat:
    max-swallow-size: 100MB
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/tutor_linking
    username: root
    password: 519216
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: tutor.linking@gmail.com
    password: lvgaluvtmctkerao
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: "http://localhost:8080/api/v1/"
jwt:
  secret-key: "8d9d5e010c2cb62a01135d1f9cac76748d604b902d57c2e98665253df1809ad8"
  expiration-time: 86400000 # a day
  refreshable-time: 604800000 # 7 days
gg-driver:

  avt-folder-id: "1mymQUalzbrRICbe1-PNEJeUu75xsE9uV"
  degree-folder-id: "15YCQUW-p617aC4LhRWWiBgeN9ANwptbl"

